<?php

return [
    'statusStyleTextBox' => array(
        ' ',
        'form-control-blue-fill',
        'form-control-red-fill',
        'form-control-purple-fill',
        'form-control-orange-fill',
        'form-control-green-fill',
    ),
    'hasStyleTextBox' => array(
        ' ',
        'form-control-green-fill',
        'form-control-red-fill',
    ),
    'hasIconStyle' => array(
        ' ',
        'font-icon-ok',
        'font-icon-del',
    ),
    'hasColorStyle' => array(
        ' ',
        'color-green',
        'color-red',
    ),
    'stateLabel' => array(
        'label-default',
        'label-primary',
        'label-danger',
        'label-info',
        'label-warning',
        'label-success',
    ),
    'hasState' => array(
        ' ',
        'success',
        'danger',
    ),
    'numbers' => array(
            'One',
            'Two',
            'Three',
            'Four',
            'Five',
            'Six',
            'Seven',
            'Eight',
            'Nine',
            'Ten',
            'Eleven',
            'Twelve',
            'Thirteen',
            'Fourteen',
            'Fifteen',
            'Sixteen',
            'Seventeen',
            'Eighteen',
            'Nineteen',
            'Twenty',
            'TwentyOne',
            'TwentyTwo',
            'TwentyThree',
            'TwentyFour',
            'TwentyFive',
            'TwentySix',
            'TwentySeven',
            'TwentyEight',
            'TwentyNine',
        ),
];
